name: Publish docs site to GitHub Pages
on:
  # repository_dispatch:
  #   types: [npm-published]
  push:
    branches:
      - "*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      - run: npm install --frozen-lockfile
      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "joao.mag.freitas@gmail.com"
          git config --list
      - run: git config --list && npm run docs:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
